name: Build RVMob (non-release)

on:
  push:

jobs: 
  # build-win:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3
  #     - name: Set up Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: "yarn"
  #     - name: Set up Java
  #       uses: actions/setup-java@v3
  #       with: 
  #         java-version: '11'
  #         distribution: 'microsoft'
  #     - name: Install and prepare dependencies
  #       run: yarn install && npx rn-nodeify -e
  #     - name: Build the app
  #       run: npx react-native build-android --mode debug
  #     - name: Upload debug APK
  #       uses: actions/upload-artifact@v3
  #       with: 
  #         path: D:\a\rvmob\rvmob\android\app\build\outputs\apk\debug\app-debug.apk
  #         name: RVMob-Debug-${{ github.sha }}.apk
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - name: Set up Java
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'microsoft'
      - name: Install and prepare dependencies
        run: yarn install && npx rn-nodeify -e && npx react-native-asset
      - name: Bundle the JS
        run: npx react-native bundle --platform android --entry-file ./index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
      - name: Build the app
        run: npx react-native build-android --mode debug && ls android/app/build/ && ls android/app/build/outputs/apk/
      - name: Prepare debug APK
        run: mv app-debug.apk RVMob-Debug-${{ github.sha }}.apk
        working-directory: /home/runner/work/rvmob/rvmob/android/app/build/outputs/apk/debug/
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with: 
          path: /home/runner/work/rvmob/rvmob/android/app/build/outputs/apk/debug/RVMob-Debug-${{ github.sha }}.apk
